// GENERATED by `npm run data:catalog` — do not edit by hand.
//
// Every size and count here is measured from the real payloads that the app downloads
// and caches, so the numbers the UI shows match what the user actually transfers.
// Regenerate after refreshing the content cache (see scripts/fetch-content.ts).

import { toArabicDigits } from '@/data/surahs';

export interface TafsirEdition {
  /** Stable id used in saved settings. */
  id: string;
  titleAr: string;
  authorAr: string;
  blurb: string;
  /** Upstream folder name in spa5k/tafsir_api. */
  slug: string;
  /** Ayahs the edition covers. Jalalayn leaves some without commentary. */
  ayahs: number;
  /** Number of surahs the upstream source actually has a file for. */
  surahs: number;
  /** Total download size in bytes across every surah. */
  totalBytes: number;
  /** Per-surah download size in bytes, index 1..114. 0 means "not available". */
  surahBytes: number[];
  /** Rough guidance shown before a heavy download. */
  weight: 'light' | 'medium' | 'heavy';
}

export interface HadithBook {
  id: string;
  titleAr: string;
  authorAr: string;
  /** Upstream file name in fawazahmed0/hadith-api. */
  slug: string;
  count: number;
  downloadBytes: number;
}

const TAFSIR_WEIGHT: Record<TafsirEdition['id'], TafsirEdition['weight']> = {
  muyassar: 'light',
  jalalayn: 'light',
  wasit: 'medium',
  saadi: 'medium',
  baghawi: 'medium',
  qurtubi: 'heavy',
  tabari: 'heavy',
  ibn_kathir: 'heavy',
};

/** The eight Arabic tafsirs offered, smallest first. */
export const TAFSIR_EDITIONS: TafsirEdition[] = [
  {
    id: 'muyassar',
    titleAr: 'التفسير الميسر',
    authorAr: 'مجموعة من العلماء',
    blurb: 'مختصر ميسّر يشرح المعنى الإجمالي لكل آية، أنسب للقارئ المبتدئ.',
    slug: 'ar-tafsir-muyassar',
    ayahs: 6236,
    surahs: 114,
    totalBytes: 3151034,
    weight: TAFSIR_WEIGHT.muyassar,
    surahBytes: [0, 5249, 172461, 99489, 98469, 75546, 91000, 101014, 38096, 69972, 52735, 55749, 47431, 24242, 27835, 36557, 60867, 50442, 46807, 30271, 48993, 42134, 49908, 34947, 36880, 37596, 94512, 48200, 38806, 32519, 29092, 15938, 13755, 42289, 26432, 28120, 28919, 61655, 35253, 39366, 40490, 27977, 30249, 39279, 29641, 16571, 17269, 21388, 22229, 10116, 16049, 29934, 26240, 36969, 17398, 19990, 33443, 16039, 13576, 14138, 9231, 7280, 6285, 6442, 8662, 10045, 7790, 15059, 40551, 32577, 32745, 31704, 15842, 12415, 46378, 21348, 19576, 31397, 18077, 26853, 24306, 38183, 11898, 25969, 17685, 25725, 11196, 13362, 11826, 16891, 9518, 16234, 10875, 6106, 3281, 7369, 16198, 1459, 3339, 3441, 2473, 2136, 2952, 2198, 2106, 1564, 2047, 1967, 1209, 1616, 1295, 1699, 1426, 1349, 1348],
  },
  {
    id: 'jalalayn',
    titleAr: 'تفسير الجلالين',
    authorAr: 'المحلّي والسيوطي',
    blurb: 'مختصر جداً يركّز على المعنى المباشر للآية.',
    slug: 'ar-tafsir-al-jalalayn',
    ayahs: 6010,
    surahs: 114,
    totalBytes: 3081246,
    weight: TAFSIR_WEIGHT.jalalayn,
    surahBytes: [0, 3747, 274668, 144402, 154155, 107196, 109179, 109932, 46458, 87614, 58325, 63063, 63938, 31518, 28568, 26997, 68837, 65940, 65942, 41976, 56474, 50735, 48338, 41893, 52479, 39488, 46796, 51933, 53431, 35818, 30123, 18927, 12646, 45843, 31849, 25517, 33141, 47556, 34107, 35667, 37320, 19295, 28824, 32752, 16208, 17145, 23773, 22546, 22753, 15383, 18184, 18507, 15790, 19569, 21658, 13462, 19093, 18786, 12764, 13414, 13596, 7648, 6705, 5628, 6739, 9789, 10708, 14130, 14333, 12298, 9997, 8375, 12434, 10415, 13247, 9552, 9243, 9815, 11327, 11958, 8211, 7146, 4128, 8581, 6251, 5615, 4578, 4472, 4845, 7825, 4882, 3392, 5138, 2872, 1616, 2697, 5059, 1837, 3457, 2073, 3029, 2536, 2154, 759, 2291, 2350, 1123, 1320, 963, 1233, 1315, 2343, 1185, 1382, 2209],
  },
  {
    id: 'wasit',
    titleAr: 'التفسير الوسيط',
    authorAr: 'الشيخ محمد سيد طنطاوي',
    blurb: 'تفسير معاصر يجمع بين الأصالة ومعالجة قضايا العصر.',
    slug: 'ar-tafsir-al-wasit',
    ayahs: 6236,
    surahs: 114,
    totalBytes: 18133632,
    weight: TAFSIR_WEIGHT.wasit,
    surahBytes: [0, 39552, 2011374, 1164822, 1258860, 1036763, 626981, 702989, 460347, 694794, 376924, 395908, 320597, 170547, 196771, 213284, 411894, 450993, 306797, 188172, 263539, 220843, 219144, 172972, 247033, 156459, 205067, 190290, 196827, 133272, 107836, 74319, 51409, 250241, 144348, 122439, 140641, 173983, 168181, 188859, 158086, 117322, 116134, 148287, 63222, 71486, 94120, 93366, 101825, 79269, 68899, 65464, 46709, 115356, 81729, 108354, 105135, 115622, 93548, 97713, 83348, 43388, 58152, 47979, 40133, 65753, 56690, 68416, 84674, 61477, 46629, 51097, 61226, 59177, 68524, 58756, 49353, 35400, 47312, 52662, 37814, 31675, 20682, 35958, 24377, 26365, 24713, 27203, 23587, 43845, 28725, 19736, 20003, 23472, 20574, 16477, 23947, 10878, 14182, 15782, 11454, 9092, 8710, 6170, 8753, 7204, 6614, 6606, 4820, 6868, 2945, 7450, 5758, 5436, 7894],
  },
  {
    id: 'saadi',
    titleAr: 'تفسير السعدي',
    authorAr: 'الشيخ عبد الرحمن بن ناصر السعدي',
    blurb: 'موجز، يعتمد على الفوائد العملية والقيم السلوكية.',
    slug: 'ar-tafsir-as-saadi',
    ayahs: 6236,
    surahs: 114,
    totalBytes: 39045656,
    weight: TAFSIR_WEIGHT.saadi,
    surahBytes: [0, 57116, 1080862, 821145, 914564, 590738, 752855, 4917004, 232179, 418919, 551053, 1117857, 588456, 134359, 198156, 391607, 346913, 330107, 1009138, 392873, 773102, 679404, 275733, 636126, 466882, 514558, 2354945, 1047560, 3315154, 218287, 178444, 198577, 80734, 460295, 249930, 150034, 567424, 886619, 628818, 282598, 782964, 189634, 218063, 430530, 306454, 144295, 112076, 97825, 93648, 71724, 127889, 212989, 349135, 570581, 249167, 382928, 407818, 131862, 76579, 549929, 151449, 74753, 38242, 42067, 53717, 55173, 50813, 79205, 216362, 186073, 181173, 298138, 90796, 76500, 338276, 109245, 438126, 93017, 100380, 118612, 131418, 163902, 27697, 107250, 80314, 208928, 80217, 114526, 118530, 74819, 122454, 66339, 156906, 52134, 29643, 24299, 96229, 12353, 37387, 18603, 42256, 27472, 25019, 5340, 18543, 7608, 5675, 17755, 5919, 6267, 8262, 10108, 5875, 9228, 17049],
  },
  {
    id: 'baghawi',
    titleAr: 'معالم التنزيل',
    authorAr: 'الإمام الحسين بن مسعود البغوي',
    blurb: 'موجز بالأثر، ينتقي من أقوال السلف.',
    slug: 'ar-tafsir-al-baghawi',
    ayahs: 6236,
    surahs: 114,
    totalBytes: 38629513,
    weight: TAFSIR_WEIGHT.baghawi,
    surahBytes: [0, 375112, 3940425, 1719468, 1535255, 1082408, 1017535, 1563152, 677775, 1188098, 491468, 630542, 713471, 285586, 262456, 429441, 551657, 905432, 795711, 449797, 656662, 700051, 405927, 534423, 521294, 407302, 886499, 481013, 453683, 344169, 301188, 158058, 179246, 702060, 298648, 232795, 379445, 794049, 413029, 488106, 371892, 249701, 261021, 447078, 303891, 136305, 229465, 180240, 298906, 118866, 209815, 227563, 243012, 300498, 212701, 467404, 471553, 161465, 148848, 243226, 103922, 49346, 239220, 62981, 64116, 79471, 79476, 111134, 385000, 234366, 163329, 110424, 106898, 189467, 216840, 190147, 151974, 165498, 210481, 150575, 172670, 126778, 74443, 167852, 106546, 117552, 56210, 78474, 122102, 172999, 89776, 59875, 68078, 87495, 46165, 30406, 90591, 70008, 47338, 57839, 38548, 23324, 45915, 10185, 23991, 37728, 26810, 32484, 18795, 20469, 58476, 21130, 33101, 20562, 74247],
  },
  {
    id: 'qurtubi',
    titleAr: 'الجامع لأحكام القرآن',
    authorAr: 'الإمام محمد بن أحمد القرطبي',
    blurb: 'تفسير فقهي شامل: الأحكام والقراءات وأسباب النزول.',
    slug: 'ar-tafseer-al-qurtubi',
    ayahs: 6236,
    surahs: 114,
    totalBytes: 78047994,
    weight: TAFSIR_WEIGHT.qurtubi,
    surahBytes: [0, 273003, 6397902, 2832052, 3171765, 2401829, 1323707, 1258166, 616263, 1276809, 360660, 2359216, 1318578, 446218, 437491, 417858, 672545, 787963, 2463989, 3143510, 2477840, 962936, 590946, 825077, 1996296, 631658, 3395424, 1960862, 1231249, 537111, 482627, 186392, 155830, 792003, 347635, 326757, 1088764, 2859645, 1746529, 684204, 899231, 570444, 511605, 535773, 254790, 111348, 253894, 212197, 216611, 232990, 558089, 579389, 574275, 1250143, 685459, 1081112, 1504452, 295637, 241487, 289871, 132472, 105502, 134013, 53122, 80982, 197644, 120946, 91240, 370605, 477410, 368613, 125762, 347478, 329276, 868319, 536605, 468199, 588458, 644822, 964178, 466908, 848256, 107681, 412440, 326814, 248221, 139663, 132037, 116406, 190038, 117449, 64209, 188221, 131648, 44304, 40231, 67347, 52858, 82777, 63546, 69295, 62700, 77335, 10165, 53368, 60047, 41995, 183704, 35280, 109187, 19129, 42032, 118543, 198393, 22015],
  },
  {
    id: 'tabari',
    titleAr: 'جامع البيان',
    authorAr: 'الإمام محمد بن جرير الطبري',
    blurb: 'من أوسع التفاسير وأقدمها، ينقل الأقوال بالإسناد.',
    slug: 'ar-tafsir-al-tabari',
    ayahs: 6236,
    surahs: 114,
    totalBytes: 61392111,
    weight: TAFSIR_WEIGHT.tabari,
    surahBytes: [0, 268722, 7397925, 2750996, 3118630, 2444808, 1541381, 1758061, 858862, 1459824, 611244, 969009, 927882, 578554, 660156, 652913, 704766, 1015308, 1000096, 710671, 951944, 739611, 765372, 614577, 649667, 618474, 1209096, 693042, 590857, 324503, 539736, 162657, 177080, 665454, 308931, 233170, 426841, 1487104, 789492, 397588, 448528, 273170, 260332, 446025, 440062, 155612, 212080, 192662, 305997, 164575, 373361, 443401, 340062, 703960, 335931, 759331, 1124423, 189712, 121240, 175449, 117122, 73064, 65944, 72323, 81591, 231756, 73189, 105892, 393953, 322420, 458732, 134171, 233965, 190248, 665281, 578434, 218907, 390327, 428465, 526986, 440651, 409587, 94370, 359215, 351526, 256411, 304017, 161277, 211565, 504930, 418916, 248188, 383903, 135665, 118123, 246733, 221103, 70173, 31848, 181547, 78425, 109015, 190171, 17004, 166989, 184228, 81555, 270413, 116292, 40989, 45471, 114873, 88075, 95933, 39243],
  },
  {
    id: 'ibn_kathir',
    titleAr: 'تفسير ابن كثير',
    authorAr: 'الإمام إسماعيل بن عمر بن كثير',
    blurb: 'من أشهر التفاسير، يجمع أقوال السلف من القرآن والسنة بالأسانيد.',
    slug: 'ar-tafsir-ibn-kathir',
    ayahs: 6236,
    surahs: 114,
    totalBytes: 89802658,
    weight: TAFSIR_WEIGHT.ibn_kathir,
    surahBytes: [0, 182061, 6304993, 4400592, 4506077, 3862732, 2249190, 2019805, 1148517, 1340859, 689790, 792805, 828199, 494979, 542895, 752027, 831634, 966794, 1308672, 1178428, 1661988, 1180869, 815460, 1426282, 1115829, 1017101, 1924369, 829439, 819362, 564937, 762919, 396961, 285871, 1322428, 629939, 399832, 809977, 2645206, 1107101, 784544, 781309, 652708, 517805, 1144546, 1069501, 222139, 746663, 407317, 583093, 338545, 665937, 674978, 766334, 1504662, 648094, 1356609, 2803666, 505241, 332035, 589628, 265656, 186670, 149880, 217571, 140677, 161210, 385496, 234737, 1026865, 537011, 567162, 324150, 325235, 464353, 1001079, 779404, 441829, 382120, 542868, 403070, 697422, 964565, 276772, 403837, 473159, 690946, 136200, 372071, 254388, 868328, 411394, 225924, 434476, 355646, 197395, 76499, 238982, 375803, 117247, 262803, 164378, 184068, 295435, 20325, 60222, 228608, 42967, 184453, 116832, 102243, 81162, 97628, 269343, 241468, 130353],
  },
];

/** The nine Arabic hadith collections available from the source, smallest first. */
export const HADITH_BOOKS: HadithBook[] = [
  {
    id: 'arbaeen_nawawi',
    titleAr: 'الأربعون النووية',
    authorAr: 'الإمام يحيى بن شرف النووي',
    slug: 'ara-nawawi',
    count: 42,
    downloadBytes: 49340,
  },
  {
    id: 'forty_qudsi',
    titleAr: 'الأربعون القدسية',
    authorAr: 'غير مذكور في بيانات المصدر',
    slug: 'ara-qudsi',
    count: 40,
    downloadBytes: 55258,
  },
  {
    id: 'muwatta_malik',
    titleAr: 'موطأ مالك',
    authorAr: 'الإمام مالك بن أنس',
    slug: 'ara-malik',
    count: 1829,
    downloadBytes: 2150337,
  },
  {
    id: 'sunan_ibn_majah',
    titleAr: 'سنن ابن ماجه',
    authorAr: 'الإمام محمد بن يزيد بن ماجه القزويني',
    slug: 'ara-ibnmajah',
    count: 4338,
    downloadBytes: 5583102,
  },
  {
    id: 'jami_tirmidhi',
    titleAr: 'جامع الترمذي',
    authorAr: 'الإمام محمد بن عيسى الترمذي',
    slug: 'ara-tirmidhi',
    count: 3924,
    downloadBytes: 7120806,
  },
  {
    id: 'sunan_nasai',
    titleAr: 'سنن النسائي',
    authorAr: 'الإمام أحمد بن شعيب النسائي',
    slug: 'ara-nasai',
    count: 5679,
    downloadBytes: 7152291,
  },
  {
    id: 'sunan_abi_dawud',
    titleAr: 'سنن أبي داود',
    authorAr: 'الإمام سليمان بن الأشعث السجستاني',
    slug: 'ara-abudawud',
    count: 5272,
    downloadBytes: 7345422,
  },
  {
    id: 'sahih_muslim',
    titleAr: 'صحيح مسلم',
    authorAr: 'الإمام مسلم بن الحجاج النيسابوري',
    slug: 'ara-muslim',
    count: 7360,
    downloadBytes: 8685140,
  },
  {
    id: 'sahih_bukhari',
    titleAr: 'صحيح البخاري',
    authorAr: 'الإمام محمد بن إسماعيل البخاري',
    slug: 'ara-bukhari',
    count: 7580,
    downloadBytes: 9770083,
  },
];

export const DEFAULT_TAFSIR_ID = 'muyassar';

/**
 * The collection "hadith of the day" reads from.
 *
 * It is fetched once on first run so the home card works offline immediately, and it is
 * the collection the card falls back to whenever nothing else is installed. Forty hadiths
 * is the smallest real book in the catalogue, so this stays cheap.
 */
export const HADITH_OF_DAY_BOOK = 'arbaeen_nawawi';

export function getTafsirEdition(id: string): TafsirEdition | undefined {
  return TAFSIR_EDITIONS.find((e) => e.id === id);
}

export function getHadithBook(id: string): HadithBook | undefined {
  return HADITH_BOOKS.find((b) => b.id === id);
}

/** Builds the upstream URL for one surah of one tafsir edition. */
export function tafsirSurahUrl(slug: string, surah: number): string {
  return `https://cdn.jsdelivr.net/gh/spa5k/tafsir_api@main/tafsir/${slug}/${surah}.json`;
}

/** Builds the upstream URL for a whole hadith collection. */
export function hadithUrl(slug: string): string {
  return `https://cdn.jsdelivr.net/gh/fawazahmed0/hadith-api@1/editions/${slug}.json`;
}

/** Byte size of one surah of an edition, for download estimates. 0 = unavailable. */
export function surahBytes(edition: TafsirEdition, surah: number): number {
  return edition.surahBytes[surah] ?? 0;
}

/** Formats a byte count for the UI. */
export function formatBytes(bytes: number): string {
  if (bytes >= 1073741824) return `${toArabicDigits((bytes / 1073741824).toFixed(1))} GB`;
  if (bytes >= 1048576) return `${toArabicDigits((bytes / 1048576).toFixed(1))} MB`;
  if (bytes >= 1024) return `${toArabicDigits(Math.round(bytes / 1024))} KB`;
  return `${toArabicDigits(bytes)} بايت`;
}
