// Hadith grading vocabulary.
//
// This file used to be the hadith collection catalogue. It listed twelve collections with
// hand-written sizes and a `bundledByDefault` flag, and four of them — Riyad as-Salihin,
// Bulugh al-Maram, Al-Adab al-Mufrad and Sunan ad-Darimi — are not published by the source
// the app downloads from. Offering a download that always 404s is worse than not offering
// it, and a size that was guessed rather than measured misleads about data use.
//
// The catalogue now lives in `data/contentCatalog.ts`, generated by `npm run data:catalog`
// from the real payloads, so every count and byte size in the UI is measured rather than
// asserted. What remains here is the part that is genuinely hand-written: how a grading
// label is rendered.
//
// Attribution for the hadith data is in `SOURCES.md`.

export type HadithGrade = 'sahih' | 'hasan' | 'daif' | 'mawdu' | 'unknown';

export const GRADE_INFO: Record<HadithGrade, { label: string; color: string; badgeClass: string }> = {
  sahih: { label: 'صحيح', color: 'success', badgeClass: 'bg-success-100 text-success-700 dark:bg-success-900/40 dark:text-success-300' },
  hasan: { label: 'حسن', color: 'warning', badgeClass: 'bg-warning-100 text-warning-700 dark:bg-warning-900/40 dark:text-warning-300' },
  daif: { label: 'ضعيف', color: 'error', badgeClass: 'bg-error-100 text-error-700 dark:bg-error-900/40 dark:text-error-300' },
  mawdu: { label: 'موضوع', color: 'error', badgeClass: 'bg-error-200 text-error-800 dark:bg-error-900/60 dark:text-error-200' },
  unknown: { label: 'الدرجة غير متوفرة في المصدر', color: 'neutral', badgeClass: 'bg-gray-100 text-gray-500 dark:bg-gray-800 dark:text-gray-400' },
};

/**
 * Folds one of the source's grade strings onto the five labels above.
 *
 * The source writes these in English and mostly as a *reference* rather than a verdict —
 * "Sahih Muslim (536)", "Sahih Bukhari (796) Sahih Muslim (409)", "Isnaad Daif" — so this
 * matches on the word that carries the verdict and ignores the numbers. Roughly 1,900 of
 * the 36,000 hadiths carry a grade; the rest are left as `unknown` rather than guessed,
 * which is why the UI shows "الدرجة غير متوفرة في المصدر" instead of inventing one.
 *
 * Order matters and is deliberate. `hasan` is tested before `sahih` so that "Isnaad Hasan
 * Sahih Muslim" lands on حسن rather than صحيح: when the two are combined the scholars
 * conventionally honour the weaker of the two, and calling it صحيح would overstate it.
 * "Sahih Bukhari And Muslim" contains no "hasan" and is unaffected.
 */
export function normalizeGrade(grade: string | undefined): HadithGrade {
  if (!grade) return 'unknown';
  const g = grade.toLowerCase().trim();
  // Checked first: both Arabic and English, and before the sahih test on purpose.
  if (g.includes('حسن') || g.includes('hasan')) return 'hasan';
  if (g.includes('صحيح') || g.includes('sahih')) return 'sahih';
  if (g.includes('ضعيف') || g.includes('daif') || g.includes('weak')) return 'daif';
  if (g.includes('موضوع') || g.includes('mawdu') || g.includes('fabricated')) return 'mawdu';
  return 'unknown';
}
