// Quran ayah text — the complete Uthmani text of all 114 surahs.
//
// Generated by `npm run data:fetch` from Tanzil (see ATTRIBUTION.md) into
// `quran-full.json`, which holds every one of the 6236 ayahs. That file replaces what
// used to be a hand-typed subset: 22 surahs, 199 ayahs, 3.2% of the mushaf.
//
// `juz` and `page` are derived from the page map in `surahs.ts` rather than stored, so a
// text file and its juz assignment can never disagree.

import fullText from './quran-full.json';
import { SURAHS as SURAHS_META, getAyahPage, getJuzForPage, type SurahMeta } from './surahs';

export interface AyahText {
  surahId: number;
  ayahNumber: number;
  text: string;
  juz: number;
  page: number;
}

const RAW = fullText as Record<string, string[]>;

const SURAHS_META_MAP: Record<number, SurahMeta> = {};
for (const s of SURAHS_META) SURAHS_META_MAP[s.id] = s;

/**
 * Every ayah of the Quran, keyed `surah:ayah`.
 *
 * Built lazily on first access because constructing 6236 objects at import time would
 * block the first paint for no benefit until the reader is actually opened.
 */
let allAyahs: Record<string, AyahText> | null = null;

function buildIndex(): Record<string, AyahText> {
  const index: Record<string, AyahText> = {};
  for (const meta of SURAHS_META) {
    const ayahs = RAW[String(meta.id)];
    if (!ayahs) continue;
    for (let i = 0; i < ayahs.length; i++) {
      const ayahNumber = i + 1;
      const page = getAyahPage(meta, ayahNumber);
      index[`${meta.id}:${ayahNumber}`] = {
        surahId: meta.id,
        ayahNumber,
        text: ayahs[i],
        juz: getJuzForPage(page),
        page,
      };
    }
  }
  return index;
}

export const QURAN_TEXT: Record<string, AyahText> = new Proxy({} as Record<string, AyahText>, {
  get(_target, key: string) {
    allAyahs ??= buildIndex();
    return allAyahs[key];
  },
  has(_target, key: string) {
    allAyahs ??= buildIndex();
    return key in allAyahs;
  },
});

/** Ayah text for a range, always in order. */
export function getAyahs(surahId: number, fromAyah = 1, toAyah?: number): AyahText[] {
  const meta = SURAHS_META_MAP[surahId];
  if (!meta) return [];
  const raw = RAW[String(surahId)];
  if (!raw) return [];

  const start = Math.max(1, fromAyah);
  const end = Math.min(toAyah ?? meta.ayahCount, raw.length);
  const result: AyahText[] = [];
  for (let i = start; i <= end; i++) {
    const page = getAyahPage(meta, i);
    result.push({
      surahId,
      ayahNumber: i,
      text: raw[i - 1],
      juz: getJuzForPage(page),
      page,
    });
  }
  return result;
}

export function getAyah(surahId: number, ayahNumber: number): AyahText | undefined {
  const raw = RAW[String(surahId)];
  if (!raw || ayahNumber < 1 || ayahNumber > raw.length) return undefined;
  const meta = SURAHS_META_MAP[surahId];
  const page = getAyahPage(meta, ayahNumber);
  return { surahId, ayahNumber, text: raw[ayahNumber - 1], juz: getJuzForPage(page), page };
}

/**
 * True when every ayah of the surah is present. With the full text bundled this is now
 * always true, and is kept so callers keep working if the data is ever regenerated
 * with a partial source.
 */
export function hasFullText(surahId: number): boolean {
  const meta = SURAHS_META_MAP[surahId];
  if (!meta) return false;
  return (RAW[String(surahId)]?.length ?? 0) === meta.ayahCount;
}

/** True when the surah has any text at all (used to warn about a truncated dataset). */
export function hasAnyText(surahId: number): boolean {
  return (RAW[String(surahId)]?.length ?? 0) > 0;
}

/** Total ayahs across the whole mushaf. */
export const TOTAL_AYAHS = SURAHS_META.reduce((sum, s) => sum + s.ayahCount, 0);